send_request_form:
    path: /request
    defaults: { _controller: AtesVacationBundle:Default:index }

edit_request_form:
    path: /edit_request/{id}
    defaults: { _controller: AtesVacationBundle:Default:edit }