parameters:
#    ates_store.example.class: Ates\StoreBundle\Example

services:
    worktime.form.type.vacation_request:
        class: \Ates\VacationBundle\Form\Type\VacationRequestType
        tags:
            - { name: form.type, alias: vacation_request }