ates_user:
    resource: "@AtesUserBundle/Resources/config/routing.yml"
    prefix:   /

ates_store:
    resource: "@AtesVacationBundle/Resources/config/routing.yml"
    prefix:   /

AtesVacationBundle:
  resource: "@AtesVacationBundle/Controller"
  type: annotation