parameters:
#    ates_store.example.class: Ates\StoreBundle\Example

services:
#    ates_store.example:
#        class: %ates_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
