employees_vacations_homepage:
    path: /
    defaults: { _controller: AtesUserBundle:Default:index }
    
employees_vacations_profile_reguest_state:
    path: /profile/{state}
    defaults: { _controller: AtesUserBundle:Profile:show }
 
show_admin_panel:
    path: /admin
    defaults: { _controller: AtesUserBundle:Admin:showAdmin }

approve_request:
    path: /admin/approve_request/{id}
    defaults: { _controller: AtesUserBundle:Admin:approveRequest }

approve_user:
    path: /admin/approve_user/{id}
    defaults: { _controller: AtesUserBundle:Admin:approveUser }
    
delete_user_on_approving:
    path: /admin/delete_user_on_approving/{id}
    defaults: { _controller: AtesUserBundle:Admin:deleteUserOnApproving }

reject_request:
    path: /admin/reject_request/{id}
    defaults: { _controller: AtesUserBundle:Admin:rejectRequest }
    
add_holiday:
    path: /admin/add_holiday
    defaults: { _controller: AtesUserBundle:Admin:addHoliday }
    
edit_holiday_form:
    path: /admin/edit_holiday/{id}
    defaults: { _controller: AtesUserBundle:Admin:editHoliday }
    
delete_holiday:
    path: /admin/delete_holiday/{id}
    defaults: { _controller: AtesUserBundle:Admin:deleteHoliday }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
